### ISSUE TITLE
error: resource android:attr/dialogCornerRadius not found.

### ISSUE THREAD

**Issue by rickie** [4face-studi0/MaterialBottomBar#6]
I tried to import your library in my project, but I got the following error: 
> error: resource android:attr/dialogCornerRadius not found.

When I click the error in Android Studio I get redirected to a file v28\values-v28.xml. This is a snippet of the file:
```
    <style name="Base.V28.Theme.AppCompat.Light" parent="Base.V26.Theme.AppCompat.Light">
        <!-- We can use the platform styles on API 28+ -->
        <item name="dialogCornerRadius">?android:attr/dialogCornerRadius</item>
    </style>

```

Can you maybe help me?

**Comment by fardavide** [comment]
@476rick  sorry for the late answer, didn't got the notification
Are you using the compileSDK 28?

**Comment by rickie** [comment]
I did not use that compileSDK. Is that really necessary? 

When I changed compileSDK version and added your library I got an error. 
I spent some time trying to fix it but it wouldn't really work. 

> Program type already present: android.support.v4.app.INotificationSideChannel
> Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel, sources=[Unknown source file], tool name=Optional.of(D8)}

Can you maybe help me?

**Comment by fardavide** [comment]
@476rick that's because you updated the compileSDK to 28, but not your support libraries, use the latest 28 version for them.

`implementation "com.android.support:xxx:28.0.0-rc02"`

Where _xxx_ could be _design_ , _support_  or _appcompat-7_ , just update the version for the libraries you are using 
 

https://stackoverflow.com/q/50289355/6372379

**Comment by rickie** [comment]
@4face-studi0  thanks for your reactions!

I updated my support libraries. I get the following error when I add your libary:

> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-rc01] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-rc01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-25:19 to override.

When I do that and add that to my manifest, then I get the next error:

> More than one file was found with OS independent path 'META-INF/android.support.design_material.version'

Can you maybe fix this?

**Comment by fardavide** [comment]
@476rick I believe that's because the library is using AndroidX while you are using the "legacy" libraries... I think the only solution is to migrate to AndroidX, if it's a small project I suggest you to do the migration, otherwise maybe I should find a solution for that.

**Comment by rickie** [comment]
OK! Thank you for your help :)

**Comment by fardavide** [comment]
@476rick Is the problem solved? I'm updating the lib actually :)

**Comment by latung** [comment]
![image](https://user-images.githubusercontent.com/44765871/55207339-4576a780-520c-11e9-83e6-67095b46a9ee.png)
 help my. thanks

**Comment by fardavide** [comment]
@latung You should update to AndroidX; I don't know if that's possible with React Native.
